###1
POST http://localhost:8090/rest/bank-book
Content-Type: application/json

{
  "userId": "4",
  "number": "num2",
  "amount": "3500",
  "currency": "EUR"
}

###2
GET http://localhost:8090/rest/bank-book/10

###3
GET http://localhost:8090/rest/bank-book/by-user-id/4

###4
DELETE http://localhost:8090/rest/bank-book/4

###5
DELETE http://localhost:8090/rest/bank-book/by-user-id/2

###6
PUT http://localhost:8090/rest/bank-book
Content-Type: application/json

{
  "id": 1,
  "userId": "2",
  "number": "num2",
  "amount": "1350",
  "currency": "RUB"
}

###
POST http://localhost:8090/rest/user
Content-Type: application/json

{
  "id": 10,
  "name": "Natasha",
  "email": "Natasha@mail.org"
}


###
PUT http://localhost:8090/rest/user
Content-Type: application/json

{ "id": "3",
  "name": "Roman",
  "email": "roman@mail.org"
}


