###1
POST http://localhost:8090/rest/bank-book
Content-Type: application/json

{
  "userId": "8",
  "number": "num11",
  "amount": "4000",
  "currency": "RUB"
}

###2
GET http://localhost:8090/rest/bank-book/4

###3
GET http://localhost:8090/rest/bank-book/by-user-id/8

###4
DELETE http://localhost:8090/rest/bank-book/4

###5
DELETE http://localhost:8090/rest/bank-book/by-user-id/7

###6
PUT http://localhost:8090/rest/bank-book
Content-Type: application/json

{
  "id": 1,
  "userId": "5",
  "number": "num2",
  "amount": "1350",
  "currency": "RUB"
}

###7
POST http://localhost:8090/rest/user
Content-Type: application/json

{
  "id": "9",
  "name": "Romario",
  "email": "romario@mail.org"
}


###8
PUT http://localhost:8090/rest/user
Content-Type: application/json

{ "id": "6",
  "name": "Roma",
  "email": "roma@mail.org"
}

###9
DELETE http://localhost:8090/rest/user/6


